### ISSUE TITLE
关于SUB_TOKEN的获取、确保超话签到成功

### ISSUE THREAD

**Issue by maqimakabaka** [Tigaisgzy/Little-helper#1]
- 首次获取 **SUB_TOKEN** 时需要在**个人主页-我的关注-超话**进行，并且需要下拉页面，加载出所有超话。否则会导致部分签到。

每日超话第一次签到都需要验证，需要人工先行验证一次。

**Comment by Tigaisgzy** [comment]
SUB_TOKEN直接登录浏览器网页版去拿就行了，超话签到要人工验证这个我没碰到过。加载所有超话，没有测试过量很大的超话，也没碰到过部分签到失败

**Comment by maqimakabaka** [comment]
是的，我获取subtoken的时候正巧在超话页面。测试后发现大约有只有30/40个签到成功，剩下10个再次运行依然无法签到。（可能30个是上限，也是造成需要手动验证的原因）。建议可以添加 `workflow_dispatch:  # 允许手动触发`，以便测试。总体上非常简单易用，感谢~

**Comment by Tigaisgzy** [comment]
好的
