### ISSUE TITLE
请问SUB_TOKEN有效期一年是怎么发现和验证的

### ISSUE THREAD

**Issue by zhu199604** [Tigaisgzy/Little-helper#2]
非常有用，已经配置到青龙面板了。还有请问>SUB_TOKEN有效期一年是怎么发现和验证的？

**Comment by Tigaisgzy** [comment]
直接在开发者工具中能看到cookie的具体信息，或者使用一些cookie管理工具。至于验证，我暂时还没用满一年。如果说经常在网页中重新登录的话，cookie可能会经常需要更新到脚本中

**Comment by zhu199604** [comment]
明白了，多谢。我目前想一次执行多个账号，在程序入口获取多个账号，循环调用main方法，但是遇到token过期的情况，程序会退出，请问如何优化比较合适

**Comment by Tigaisgzy** [comment]
加个判断，如果发现token过期就先记录异常并且跳过当前账号，最后发送邮件时再把成功结果与异常结果一起发送出去就行

**Comment by zhu199604** [comment]
非常感谢，已解决
